Fix error code returned from successful run
OneCDOnly/RunLast pull request #7
Opened 2020-12-21 15:29 UTC by pedropombeiro

RunLast is failing in the last line and returning exit code 1,
because the tmp file does not exist:

```
+ local last_op_line_num=146
+ head -n146 /share/CACHEDEV1_DATA/.qpkg/RunLast/RunLast.log
+ mv /share/CACHEDEV1_DATA/.qpkg/RunLast/RunLast.log.tmp /share/CACHEDEV1_DATA/.qpkg/RunLast/RunLast.log
+ [[ -e /share/CACHEDEV1_DATA/.qpkg/RunLast/RunLast.log.tmp ]]
```

2020-12-21 19:13 UTC, OneCDOnly requested changes
Ah, good pickup. 👍🏽 

Instead of that `echo`, can you please make the last line `exit 0` instead?

So, it looks like this:
```

[[ -e $TEMP_LOG_PATHFILE ]] && rm -f "$TEMP_LOG_PATHFILE"

exit 0

```

2020-12-22 09:39 UTC, pedropombeiro commented
@OneCDOnly Sounds good, changed. :thumbsup:

2020-12-22 19:16 UTC, merged

2020-12-22 19:16 UTC, OneCDOnly commented
Good work @pedropombeiro 👍🏽

2020-12-22 19:25 UTC, pedropombeiro commented
Thanks for the quick turnaround!